name: 'Build'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'csrc/**'
      - 'spec/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Lua
        uses: dwenegar/setup-lua@master
        with:
          lua-version: '5.4'
          luarocks-version: latest
      - name: Build
        run: |
          luarocks make --no-install
      - name: Test & coverage
        run: |
          luarocks install busted
          luarocks install luacov
          luarocks install luacov-coveralls
          luarocks test -- -c --run=test
          luacov-coveralls -t ${{ secrets.GITHUB_TOKEN }} --exclude "/home/runner/.+"
